// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AsyncEcho(arg1:string):Promise<string>;

export function Execute(arg1:string,arg2:Array<string>):Promise<main.CommandOutput>;

export function ExecuteInNewWindow(arg1:string,arg2:Array<string>):Promise<main.CommandOutput>;

export function Greet(arg1:string):Promise<string>;
