// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AsyncEcho(arg1) {
  return window['go']['main']['App']['AsyncEcho'](arg1);
}

export function Execute(arg1, arg2) {
  return window['go']['main']['App']['Execute'](arg1, arg2);
}

export function ExecuteInNewWindow(arg1, arg2) {
  return window['go']['main']['App']['ExecuteInNewWindow'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
